name: macOS Latest CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: udp-forwarder-macos-latest
        path: /Users/runner/work/udp-forwarder/udp-forwarder/udp-forwarder
    
