name: Ubuntu Latest CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: udp-forwarder-ubuntu-latest
        path: /home/runner/work/udp-forwarder/udp-forwarder
