name: Windows Latest CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make
      
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: udp-forwarder-windows-latest.exe
        path: udp-forwarder.exe
